# This file is editable for custom configurations

NET_SEMAPHORE = 100

TIME_OUT_MILLI_SEC = 1500
WAITING_RESPONSES_GC_SECS = TIME_OUT_MILLI_SEC*2
PING_WINDOW = 17
PING_MILLI_SECS_REDUNDANCIES = [
    (20, 2),
    (80, 4),
    (150, 8),
    (1000, 10),
]
PING_CALC_TRIM_RATIO = 0.12

class SyncIntervalSec:
    GOSSIP = 1

MAX_GOSSIP_NODES_FOR_SHARING = 4
MAX_GOSSIP_SEND_NODES = 15
MAX_GOSSIP_NODE_LIST_SIZE = 2000
MIN_GOSSIP_NODE_LIST_SIZE = 10
TTL_GOSSIP_NODE = 15

SAVED_DIR_PATH = "saved/"
STARTED_FILE_NAME = "started"

HELLO_ATTEMPTS = 3
ENCRYPTER_OTHER_PARTY_SEQ_WINDOW = 10